### ISSUE TITLE
How about restoring Noun and Adj

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [zhuang-li/FACTUAL#2]
when Input "dogs wear bags"

how to get [ dog, wear, bag ] instead of dogs and bags

**Comment by zhuang-li** [comment]
To address this, I believe you should handle the lemmatization yourself, as we consider the plural form of a noun to be an important feature. For instance, 'dogs' could be represented in an image by either a single bounding box that encompasses multiple dogs or by multiple bounding boxes, each containing a single dog. In contrast, the term 'dog' unambiguously represents just one bounding box. Therefore, the bounding box representations for 'dogs' and 'dog' differ significantly.

**Comment by ZhaoyangLi-nju** [comment]
Thanks for your reply, I got it
